package jp.velvet.yoshio.mybatis;

import java.util.List;
import jp.velvet.yoshio.mybatis.Member;
import jp.velvet.yoshio.mybatis.MemberExample;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    Member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    int updateByPrimaryKey(Member record);
    
    List<Member> selectAll();
}