package jp.velvet.yoshio.mybatis;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.ID
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.FIRST_NAME
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.LAST_NAME
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.ID
     *
     * @return the value of PUBLIC.MEMBER.ID
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.ID
     *
     * @param id the value for PUBLIC.MEMBER.ID
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.FIRST_NAME
     *
     * @return the value of PUBLIC.MEMBER.FIRST_NAME
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.MEMBER.FIRST_NAME
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.LAST_NAME
     *
     * @return the value of PUBLIC.MEMBER.LAST_NAME
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.MEMBER.LAST_NAME
     *
     * @mbggenerated Tue Apr 16 10:59:35 JST 2013
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}